use super::super::{AtomBlueprint, BondBlueprint, MoleculeTestCase};
use dreid_typer::{BondOrder, Element};

pub const ACBUOL: MoleculeTestCase = MoleculeTestCase {
    name: "ACBUOL - Cyclobutane Lactone",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_2",
        },
        AtomBlueprint {
            label: "O1",
            element: Element::O,
            charge: 0,
            expected_type: "O_2",
        },
        AtomBlueprint {
            label: "O2",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "O3",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "O4",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7c",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_O4",
            element: Element::H,
            charge: 0,
            expected_type: "H_HB",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "O3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "O4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "O1",
            order: BondOrder::Double,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "O2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "O2",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "O3",
            atom2_label: "C7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7c",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "O4",
            atom2_label: "H_O4",
            order: BondOrder::Single,
        },
    ],
};

pub const AFURPO10: MoleculeTestCase = MoleculeTestCase {
    name: "AFURPO10 - Cage Ether",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "O1",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "O2",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "O1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "O2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "O1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "O2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6b",
            order: BondOrder::Single,
        },
    ],
};

pub const ADAMANTANE: MoleculeTestCase = MoleculeTestCase {
    name: "Adamantane",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C8",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C9",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C10",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C8",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C10",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C8",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C9",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C9",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C10",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9",
            atom2_label: "H_C9a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9",
            atom2_label: "H_C9b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10",
            atom2_label: "H_C10a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10",
            atom2_label: "H_C10b",
            order: BondOrder::Single,
        },
    ],
};

pub const DECALIN: MoleculeTestCase = MoleculeTestCase {
    name: "Decalin",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C8",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C9_fused",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C10_fused",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "C7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C8",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "C9_fused",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9_fused",
            atom2_label: "C10_fused",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10_fused",
            atom2_label: "C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9_fused",
            atom2_label: "H_C9a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9_fused",
            atom2_label: "H_C9b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10_fused",
            atom2_label: "H_C10a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10_fused",
            atom2_label: "H_C10b",
            order: BondOrder::Single,
        },
    ],
};

pub const ABAXES: MoleculeTestCase = MoleculeTestCase {
    name: "ABAXES - 1,4-dithiacyclohex-2-ene",
    atoms: &[
        AtomBlueprint {
            label: "S1",
            element: Element::S,
            charge: 0,
            expected_type: "S_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_2",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_2",
        },
        AtomBlueprint {
            label: "S4",
            element: Element::S,
            charge: 0,
            expected_type: "S_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "H2",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H51",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H52",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H61",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H62",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "S1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Double,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "S4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "S4",
            atom2_label: "C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "S1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H51",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H52",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H61",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H62",
            order: BondOrder::Single,
        },
    ],
};

pub const METHYL_PYRIDINE: MoleculeTestCase = MoleculeTestCase {
    name: "ACPYNS - 4-Methyl-Pyridine",
    atoms: &[
        AtomBlueprint {
            label: "N1",
            element: Element::N,
            charge: 0,
            expected_type: "N_R",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "H2",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H5",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H6",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H71",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H72",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H73",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "N1",
            atom2_label: "C2",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C5",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C6",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "N1",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H71",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H72",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H73",
            order: BondOrder::Single,
        },
    ],
};

pub const ACRIDINE: MoleculeTestCase = MoleculeTestCase {
    name: "ACRAMS - Acridine",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C8",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C9",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "N10",
            element: Element::N,
            charge: 0,
            expected_type: "N_R",
        },
        AtomBlueprint {
            label: "C11",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C12",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C13",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "C14",
            element: Element::C,
            charge: 0,
            expected_type: "C_R",
        },
        AtomBlueprint {
            label: "H1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H2",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H4",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H7",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H8",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H11",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H12",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H13",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H14",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C5",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C6",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "C1",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C7",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C8",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "C9",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C9",
            atom2_label: "N10",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "N10",
            atom2_label: "C6",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "N10",
            atom2_label: "C11",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C11",
            atom2_label: "C12",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C12",
            atom2_label: "C13",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C13",
            atom2_label: "C14",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C14",
            atom2_label: "C9",
            order: BondOrder::Aromatic,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H8",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C11",
            atom2_label: "H11",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C12",
            atom2_label: "H12",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C13",
            atom2_label: "H13",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C14",
            atom2_label: "H14",
            order: BondOrder::Single,
        },
    ],
};
