use super::super::{AtomBlueprint, BondBlueprint, MoleculeTestCase};
use dreid_typer::{BondOrder, Element};

pub const ACBUOL: MoleculeTestCase = MoleculeTestCase {
    name: "ACBUOL - Cyclobutane Lactone",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_2",
        },
        AtomBlueprint {
            label: "O1",
            element: Element::O,
            charge: 0,
            expected_type: "O_2",
        },
        AtomBlueprint {
            label: "O2",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "O3",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "O4",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7c",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_O4",
            element: Element::H,
            charge: 0,
            expected_type: "H_HB",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "O3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "O4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "O1",
            order: BondOrder::Double,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "O2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "O2",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "O3",
            atom2_label: "C7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7c",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "O4",
            atom2_label: "H_O4",
            order: BondOrder::Single,
        },
    ],
};

pub const AFURPO10: MoleculeTestCase = MoleculeTestCase {
    name: "AFURPO10 - Cage Ether",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "O1",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "O2",
            element: Element::O,
            charge: 0,
            expected_type: "O_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "O1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "O2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "O1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "O2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6b",
            order: BondOrder::Single,
        },
    ],
};

pub const ADAMANTANE: MoleculeTestCase = MoleculeTestCase {
    name: "Adamantane",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C8",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C9",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C10",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C8",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C10",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C8",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C9",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C9",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C10",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9",
            atom2_label: "H_C9a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9",
            atom2_label: "H_C9b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10",
            atom2_label: "H_C10a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10",
            atom2_label: "H_C10b",
            order: BondOrder::Single,
        },
    ],
};

pub const DECALIN: MoleculeTestCase = MoleculeTestCase {
    name: "Decalin",
    atoms: &[
        AtomBlueprint {
            label: "C1",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C2",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C3",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C4",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C5",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C6",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C7",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C8",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C9_fused",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "C10_fused",
            element: Element::C,
            charge: 0,
            expected_type: "C_3",
        },
        AtomBlueprint {
            label: "H_C1",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C2b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C3b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C4b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C5b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C6",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C7b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C8b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C9b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10a",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
        AtomBlueprint {
            label: "H_C10b",
            element: Element::H,
            charge: 0,
            expected_type: "H_",
        },
    ],
    bonds: &[
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "C2",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "C3",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "C4",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "C5",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "C7",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "C8",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "C9_fused",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9_fused",
            atom2_label: "C10_fused",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10_fused",
            atom2_label: "C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C1",
            atom2_label: "H_C1",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C2",
            atom2_label: "H_C2b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C3",
            atom2_label: "H_C3b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C4",
            atom2_label: "H_C4b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C5",
            atom2_label: "H_C5b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C6",
            atom2_label: "H_C6",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C7",
            atom2_label: "H_C7b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C8",
            atom2_label: "H_C8b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9_fused",
            atom2_label: "H_C9a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C9_fused",
            atom2_label: "H_C9b",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10_fused",
            atom2_label: "H_C10a",
            order: BondOrder::Single,
        },
        BondBlueprint {
            atom1_label: "C10_fused",
            atom2_label: "H_C10b",
            order: BondOrder::Single,
        },
    ],
};
