# ==============================================================================
#  Official DREIDING Atom Typing Ruleset for dreid-typer
#  Version: 1.0.0
#  Author: Tony Kan, William A. Goddard III
# ==============================================================================

# ------------------------------------------------------------------------------
# §1. Special Hydrogen Types (Highest Priority)
#    These rules rely on iterative typing of their neighbors.
# ------------------------------------------------------------------------------

[[rule]]
name = "H_Bridge_Diborane"
priority = 500
type = "H_b"
conditions = { element = "H", degree = 2, neighbor_elements = { B = 2 } }

# ------------------------------------------------------------------------------
# §2. Aromatic Types (High Priority)
#    Aromaticity is a strong, non-local feature that should be typed first.
# ------------------------------------------------------------------------------

[[rule]]
name = "C_Aromatic"
priority = 400
type = "C_R"
conditions = { element = "C", is_aromatic = true }

[[rule]]
name = "N_Aromatic"
priority = 400
type = "N_R"
conditions = { element = "N", is_aromatic = true }

# ------------------------------------------------------------------------------
# §3. Master Rules Based on Geometry (Steric Numbers)
#    Directly Mapping VSEPR Theory to the DREIDING Type.
# ------------------------------------------------------------------------------

[[rule]]
name = "C_Linear_SP"
priority = 300
type = "C_1"
conditions = { element = "C", steric_number = 2 }

[[rule]]
name = "N_Linear_SP"
priority = 300
type = "N_1"
conditions = { element = "N", steric_number = 2 }

[[rule]]
name = "C_Trigonal_SP2"
priority = 200
type = "C_2"
conditions = { element = "C", steric_number = 3, is_aromatic = false }

[[rule]]
name = "N_Trigonal_SP2"
priority = 200
type = "N_2"
conditions = { element = "N", steric_number = 3, is_aromatic = false }

[[rule]]
name = "O_Trigonal_SP2"
priority = 200
type = "O_2"
conditions = { element = "O", steric_number = 3 }

[[rule]]
name = "B_Trigonal_SP2"
priority = 200
type = "B_2"
conditions = { element = "B", steric_number = 3 }

[[rule]]
name = "S_Trigonal_SP2"
priority = 200
type = "S_2"
conditions = { element = "S", steric_number = 3, is_aromatic = false }

[[rule]]
name = "C_Tetrahedral_SP3"
priority = 100
type = "C_3"
conditions = { element = "C", steric_number = 4 }

[[rule]]
name = "N_Tetrahedral_SP3"
priority = 100
type = "N_3"
conditions = { element = "N", steric_number = 4 }

[[rule]]
name = "O_Tetrahedral_SP3"
priority = 100
type = "O_3"
conditions = { element = "O", steric_number = 4 }

[[rule]]
name = "P_Tetrahedral_SP3"
priority = 100
type = "P_3"
conditions = { element = "P", steric_number = 4 }

[[rule]]
name = "S_Default_SP3"
priority = 100
type = "S_3"
conditions = { element = "S", hybridization = "SP3" }

[[rule]]
name = "Si_Tetrahedral_SP3"
priority = 100
type = "Si3"
conditions = { element = "Si", steric_number = 4 }

[[rule]]
name = "B_Tetrahedral_SP3"
priority = 100
type = "B_3"
conditions = { element = "B", steric_number = 4 }

[[rule]]
name = "Al_Tetrahedral_SP3"
priority = 100
type = "Al3"
conditions = { element = "Al", steric_number = 4 }

[[rule]]
name = "Ge_Tetrahedral_SP3"
priority = 100
type = "Ge3"
conditions = { element = "Ge", steric_number = 4 }

[[rule]]
name = "As_Tetrahedral_SP3"
priority = 100
type = "As3"
conditions = { element = "As", steric_number = 4 }

[[rule]]
name = "Se_Tetrahedral_SP3"
priority = 100
type = "Se3"
conditions = { element = "Se", steric_number = 4 }

[[rule]]
name = "Sn_Tetrahedral_SP3"
priority = 100
type = "Sn3"
conditions = { element = "Sn", steric_number = 4 }

[[rule]]
name = "Sb_Tetrahedral_SP3"
priority = 100
type = "Sb3"
conditions = { element = "Sb", steric_number = 4 }

[[rule]]
name = "Te_Tetrahedral_SP3"
priority = 100
type = "Te3"
conditions = { element = "Te", steric_number = 4 }

# ------------------------------------------------------------------------------
# §4. Iterational Rules (High Priority, Depends on Neighbor Type)
#    Rules executed after the neighbor type is determined.
# ------------------------------------------------------------------------------

[[rule]]
name = "O_Aromatic_Or_Conjugated"
priority = 401
type = "O_R"
conditions = { element = "O", hybridization = "Resonant" }

[[rule]]
name = "H_Hydrogen_Bond_Donor_On_O"
priority = 250
type = "H_HB"
conditions = { element = "H", degree = 1, neighbor_types = { O_3 = 1 } }

[[rule]]
name = "H_Hydrogen_Bond_Donor_On_N"
priority = 249
type = "H_HB"
conditions = { element = "H", degree = 1, neighbor_types = { N_3 = 1 } }

[[rule]]
name = "H_Hydrogen_Bond_Donor_On_Aromatic_N"
priority = 248
type = "H_HB"
conditions = { element = "H", degree = 1, neighbor_types = { N_R = 1 } }

# ------------------------------------------------------------------------------
# §5. Fallback Rules (Low Priority)
#    Generic rules to ensure all atoms are typed.
# ------------------------------------------------------------------------------

[[rule]]
name = "Halogen_F"
priority = 50
type = "F_"
conditions = { element = "F" }

[[rule]]
name = "Halogen_Cl"
priority = 50
type = "Cl_"
conditions = { element = "Cl" }

[[rule]]
name = "Halogen_Br"
priority = 50
type = "Br_"
conditions = { element = "Br" }

[[rule]]
name = "Halogen_I"
priority = 50
type = "I_"
conditions = { element = "I" }

# ------------------------------------------------------------------------------
# §6. Metals & Ions (Low Priority)
#    These are typically isolated atoms (degree=0).
# ------------------------------------------------------------------------------

[[rule]]
name = "Ion_Na"
priority = 20
type = "Na"
conditions = { element = "Na" }

[[rule]]
name = "Ion_Ca"
priority = 20
type = "Ca"
conditions = { element = "Ca" }

[[rule]]
name = "Ion_Fe"
priority = 20
type = "Fe"
conditions = { element = "Fe" }

[[rule]]
name = "Ion_Zn"
priority = 20
type = "Zn"
conditions = { element = "Zn" }

[[rule]]
name = "Ion_Mg"
priority = 20
type = "Mg"
conditions = { element = "Mg" }

[[rule]]
name = "Ion_Mn"
priority = 20
type = "Mn"
conditions = { element = "Mn" }

[[rule]]
name = "Ion_Ti"
priority = 20
type = "Ti"
conditions = { element = "Ti" }

[[rule]]
name = "Ion_Tc"
priority = 20
type = "Tc"
conditions = { element = "Tc" }

[[rule]]
name = "Ion_Ru"
priority = 20
type = "Ru"
conditions = { element = "Ru" }

[[rule]]
name = "Ion_Hg"
priority = 20
type = "Hg"
conditions = { element = "Hg" }

# ------------------------------------------------------------------------------
# §7. Standard Hydrogen Default (Lowest Priority)
#    This rule catches any hydrogen atom not already typed as acidic or bridging.
# ------------------------------------------------------------------------------

[[rule]]
name = "H_Standard_Default"
priority = 1
type = "H_"
conditions = { element = "H" }
